### PR TITLE
refactor: replica listing based on query

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**
### What does this PR do?
- Refactors the replica list by query feature.

### Why do we need this PR?
- This simplifies the query and increases maintainability.

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors cancel

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors cancel

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors cancel

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Pull request merged**
