### PR TITLE
test(volume/resize): stability fixes in offline volume resize test

### PR DESCRIPTION
**Pull request by dsharma-dc**

### CODE REVIEW

**Comment by dsharma-dc** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by dsharma-dc** [comment]
unrelated failure in test: test_outofspace_condition_does_not_affect_thick_volumes_on_mixed_pools

bors try

**Comment by dsharma-dc** [comment]
> ## try
> Build failed:
> 
> * [continuous-integration/jenkins/branch](https://mayastor-ci.mayadata.io/job/Mayastor-Control-Plane/job/trying/27/display/redirect)

It's the events cargo test this time

```
failures:
    event::events
test result: FAILED. 43 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 409.77s
```
@datacore-vvarakantham

**Comment by dsharma-dc** [comment]
bors merge

**Pull request merged**
