### PR TITLE
chore: update nixpkgs to 22.11

### PR DESCRIPTION
**Pull request by tiagolobocastro**
This brings a newer nvme-cli and thus we don't need to make it special.

### CODE REVIEW

**Review by chriswldenyer — APPROVED** [review]
Looks reasonable

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
