### PR TITLE
fix(replica-openapi): revert back changes for poolid in Replica & ReplicaSpec openapi

### PR DESCRIPTION
**Pull request by Ab-hishek**
This change is needed so that no breaking change is experienced in terms of system tests.

Signed-off-by: Abhishek Agarwal <abhiagarwal.agarwal2@gmail.com>

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
Aren't we missing changes on the `From<xxx> To <Replica>` to use the changed field name pool?

**Comment by Ab-hishek** [comment]
That is not required coz the models for openapi are auto generated and regarding conversion from any type to the `models::Replica` is done via a function where we pass parameters and have a `From` trait implemented for it. And for `poolid` since its of a type macro rule, the required conversions are already implemented.

**Comment by tiagolobocastro** [comment]
> That is not required coz the models for openapi are auto generated and regarding conversion from any type to the `models::Replica` is done via a function where we pass parameters and have a `From` trait implemented for it. And for `poolid` since its of a type macro rule, the required conversions are already implemented.

No, it's because openapi::models::Replica is created via a function so the parameters are unnamed; as longer as the order is kept no changes should be required.

**Comment by Ab-hishek** [comment]
Yeah, I meant the sequence of parameters are not changed.

**Comment by Ab-hishek** [comment]
bors merge

**Pull request merged**
