### PR TITLE
Allow expansion of volumes with snapshots, or restored volumes

### PR DESCRIPTION
**Pull request by dsharma-dc**

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]
LGTM

**Review by tiagolobocastro — APPROVED** [review]
Something like this:
'Allow expansion for volumes with snapshots, or restored volumes'

**Comment by dsharma-dc** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
You forgot to change the PR title as well

**Comment by dsharma-dc** [comment]
> You forgot to change the PR title as well

Done now (y). Had changed commit title though.

**Comment by tiagolobocastro** [comment]
You had to cancel bors... got merged with wrong title...

**Comment by dsharma-dc** [comment]
> You had to cancel bors... got merged with wrong title...

Ah, bummer. Not a big deal I guess? the PR title just gets embedded in the description of merge commit. And it's not wrong per se, just needed rewording.

**Comment by tiagolobocastro** [comment]
Yeah no biggie

**Pull request merged**
