### PR TITLE
chore(eventing): update mayastor-dependency submodule for mbus api

### PR DESCRIPTION
**Pull request by sinhaashish**

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]
Please revert the rpc/api update, you only need to update the dependencies here right?

**Comment by sinhaashish** [comment]
> Please revert the rpc/api update, you only need to update the dependencies here right?

done

**Comment by sinhaashish** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by sinhaashish** [comment]
bors merge

**Pull request merged**
