### PR TITLE
Capacity - add storage usage to agents rpc and openapi

### PR DESCRIPTION
**Pull request by tiagolobocastro**
feat(plugin): format byte size into appropriate unit
    
    Used the human read crate to format it.
    Also convert block size in blocks to a size.
    The doc mention that the size is in 512 blocks, is this really always true? Even
    if the device is 4k?
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    refactor(plugin): add new row trait to simplify single row resources
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(capacity/thin/plugin): add usage to rest plugin
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(capacity/thin/openapi): add volume and replica usage the openapi
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(capacity/thin/rpc): add volume and replica usage to the agents rpc
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
