### PR TITLE
chore: update policy document signpost links

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by avishnu — APPROVED** [review]

**Comment by niladrih** [comment]
bors merge

**Review by edrob999 — APPROVED** [review]
:thumbsup:
Signed-off-by: Ed Robinson <ed.robinson@gmail.com>

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Pull request merged**
