### PR TITLE
Cargo upgrade

### PR DESCRIPTION
**Pull request by tiagolobocastro**
chore: use lld in the dev shell
    
    This addresses memory usage issues on CI (though happen locally as well)
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    build: upgrade rust to 05/10 nightly and 1.72.1 stable
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    build(nix): replace deprecated contents with copyToRoot
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    chore: silence async_nats crate debug logs
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    build: upgrade rust crates
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    build: update cargo deps
    
    Updates cargo deps from toml file.
    Next set of changes will upgrade versions.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    ci: disable cargo incremental compilation
    
    There's no benefit to having this on CI and it takes up more space..
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors ping

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
