### PR TITLE
chore(replica_stat_rpc): update protobuf

### PR DESCRIPTION
**Pull request by abhilashshetty04**

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors try

**Comment by abhilashshetty04** [comment]
bors cancel

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by pchandra19** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors merge

**Pull request merged**
