### PR TITLE
fix(agent-node/subsystem): a subsystem can have more than 1 controller

### PR DESCRIPTION
**Pull request by tiagolobocastro**
chore(ci): set target test branch automatically
    
    Add script that determines the appropriate branch of dataplane to test against and writes
    this to a rust file.
    This is to avoid having to modify this file when we create a release branch.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(agent-node/subsystem): handle multiple controller paths
    
    The existing code seems to treat a subsystem as having a single path.
    The nvmeadm library subsystem type seems to be quite confusing using the term controller
    and subsystem interchangeably.
    This poses a problem when swithching over as temporarily the subsystem will have two controllers,
    the new one (good) and the old one (bad).
    
    Here we can see the old controller nvme0 and the new one nvme1 by probing sysfs at the right time:
    tiago@ksnode-2:~$ ls /sys/class/nvme-subsystem/nvme-subsys0/
    model  ng0n1  nvme0n1 (block device is still 0)  nvme0 (old) nvme1 (new)  subsysnqn ..
    
    What was then happening is that when fixing a path to live we were setting the suspected_path nvme0
    as Good, rather than leave nvme0 as Bad and set nvme1 as Good.
    This posed a problem on a subsequent failure as we would even try to disconnect nvme0 instead of
    nvme1 - this could cause us to boot the wrong controller and causing issues on another disk!!!
    
    This fix is to keep a list of paths per NQN on the detector. Additionally when we fetch a controller
    per NQN we have to fetch a list instead (again, multiple paths for the same NQN...)
    
    Ideally we should fix things properly (nvmeadm) but nearing the release this is probably less risky.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(agent-node): verify nqn when disconnecting
    
    When attempting to disconnect a path, make sure that the nqn is the same.
    Why? We found a bug where we would keep a stale path, and it's possible that a new device
    may be reuse that path (new nqn ofc) and so we should ensure the nqn is the expected
    when disconnecting to make sure we don't remove the wrong device!
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(nix-build): speedup incremental builds
    
    When building a single binary, don't bother building the rest of the binaries from a project.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(release-ci): override registry properly
    
    Previously the existing registry prefix was being kept.
    To keep existing behaviour (in case it's being used :() we only strip out the existing
    registry if the new one has a slash.
    Example:
    ./scripts/release.sh --registry mayadata would push image mayadata/openebs/$image
    ./scripts/release.sh --registry docker.io/mayadata would push image docker.io/mayadata/$image
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by avishnu — APPROVED** [review]
LGTM
On a relative front, does any of this apply to the NVMe connection handling from the CSI node agent as well?
I meant the regular connections (not HA).

**Review by mtzaurus — APPROVED** [review]

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> LGTM On a relative front, does any of this apply to the NVMe connection handling from the CSI node agent as well? I meant the regular connections (not HA).

It's generally applicable but it's only a problem when we switchover and have more than 1, so for all intents and purposes only with HA

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
