### PR TITLE
chore(dependabot): update py url lib

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Review by datacore-vvarakantham — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
