### PR TITLE
test(upgrade-rebuild): add upgrade test

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add a test which exercises the upgrade/rebuild path by draining all nodes for a certain number of iterations.
This test is disabled by default and can be run manually if we need to re-run the same test again.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by dsharma-dc — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
