### PR TITLE
ci: specify opentel receiver endpoint

### PR DESCRIPTION
**Pull request by tiagolobocastro**
When running on the CI we an opentel receiver to push the traces to an external collector.
With recent versions of the receiver, it now listens only on localhost which was prevent it from receiving the traces to begin with. Now we specify the domain name of the receiver.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
This fixes the flaky rest client test :)

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
> Operation not permitted: '/tmp/disk_0'

:open_mouth: 
Probably previous cancel killed the test without cleanup? I guess we need to ensure final cleanup does clean everything up, maybe using a specific folder within tmp to make it easier to cleanup, example: one single rm -rf /tmp/ci-run-99

bors merge

**Pull request merged**
