### PR TITLE
feat(msp): normalize device schemas

### PR DESCRIPTION
**Pull request by gila**
As part of the MSP operator implementation support was added to validate
that devices are present. This provides more feedback to the user when
using the event system from k8s.

However, when device schemas are provided in the spec, we should
normalize before comparing them to the block devices on the targeted
nodes.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors doesn't like this PR :) let's try again...
bors merge

**Comment by paulyoong** [comment]
bors merge

**Pull request merged**
