### PR TITLE
fix: use the operation guards explicitly and rename core to controller

### PR DESCRIPTION
**Pull request by tiagolobocastro**
fix: use the operation guards explicitly

This makes the operations a lot clear by always requesting the guard ahead of time and
using it as raii properly.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

refactor: rename core's core to controller

The module core within the core agent has been a pain for quite sometime now.
Renamed to controller, which I think makes sense since it's where the reconciler and
the scheduling logic lives.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
missed something!
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
forgot to push, sigh...
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
