### PR TITLE
feat(upgrade): add constant and get functionality for upgrade

### PR DESCRIPTION
**Pull request by sinhaashish**
Signed-off-by: sinhaashish <ashi.sinha.87@gmail.com>

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by dsharma-dc — APPROVED** [review]

**Comment by sinhaashish** [comment]
bors try

**Comment by sinhaashish** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by sinhaashish** [comment]
bors try

**Comment by sinhaashish** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
hmm this should not have been merged, the rest-plugin should have no knowledge of upgrade.
Something like this on extensions would achieve the same, without breaking the boundaries:
```rust
diff --git a/k8s/plugin/src/main.rs b/k8s/plugin/src/main.rs
index ffc9450..c580c52 100644
--- a/k8s/plugin/src/main.rs
+++ b/k8s/plugin/src/main.rs
@@ -17,6 +17,8 @@ use resources::{
     upgrade::{UpgradeOperator, UpgradeResources},
     Operations,
 };
+use crate::resources::{GetResourcesK8s};
+
 pub mod constant;
 
 #[derive(Parser, Debug)]
@@ -76,36 +78,42 @@ async fn execute(cli_args: CliArgs) {
     let fut = async move {
         match cli_args.operations {
             Operations::Get(resource) => match resource {
-                GetResources::Cordon(get_cordon_resource) => match get_cordon_resource {
-                    GetCordonArgs::Node { id: node_id } => {
-                        cordon::NodeCordon::get(&node_id, &cli_args.output).await
-                    }
-                    GetCordonArgs::Nodes => cordon::NodeCordons::list(&cli_args.output).await,
-                },
-                GetResources::Drain(get_drain_resource) => match get_drain_resource {
-                    GetDrainArgs::Node { id: node_id } => {
-                        drain::NodeDrain::get(&node_id, &cli_args.output).await
-                    }
-                    GetDrainArgs::Nodes => drain::NodeDrains::list(&cli_args.output).await,
-                },
-                GetResources::Volumes => volume::Volumes::list(&cli_args.output).await,
-                GetResources::Volume { id } => volume::Volume::get(&id, &cli_args.output).await,
-                GetResources::VolumeReplicaTopology { id } => {
-                    volume::Volume::topology(&id, &cli_args.output).await
-                }
-                GetResources::Pools => pool::Pools::list(&cli_args.output).await,
-                GetResources::Pool { id } => pool::Pool::get(&id, &cli_args.output).await,
-                GetResources::Nodes => node::Nodes::list(&cli_args.output).await,
-                GetResources::Node(args) => {
-                    node::Node::get(&args.node_id(), &cli_args.output).await
+                GetResourcesK8s::UpgradeStatus => {
                 }
-                GetResources::BlockDevices(bdargs) => {
-                    blockdevice::BlockDevice::get_blockdevices(
-                        &bdargs.node_id(),
-                        &bdargs.all(),
-                        &cli_args.output,
-                    )
-                    .await
+                GetResourcesK8s::GetRest(resource) => {
+                    match resource {
+                        GetResources::Cordon(get_cordon_resource) => match get_cordon_resource {
+                            GetCordonArgs::Node { id: node_id } => {
+                                cordon::NodeCordon::get(&node_id, &cli_args.output).await
+                            }
+                            GetCordonArgs::Nodes => cordon::NodeCordons::list(&cli_args.output).await,
+                        },
+                        GetResources::Drain(get_drain_resource) => match get_drain_resource {
+                            GetDrainArgs::Node { id: node_id } => {
+                                drain::NodeDrain::get(&node_id, &cli_args.output).await
+                            }
+                            GetDrainArgs::Nodes => drain::NodeDrains::list(&cli_args.output).await,
+                        },
+                        GetResources::Volumes => volume::Volumes::list(&cli_args.output).await,
+                        GetResources::Volume { id } => volume::Volume::get(&id, &cli_args.output).await,
+                        GetResources::VolumeReplicaTopology { id } => {
+                            volume::Volume::topology(&id, &cli_args.output).await
+                        }
+                        GetResources::Pools => pool::Pools::list(&cli_args.output).await,
+                        GetResources::Pool { id } => pool::Pool::get(&id, &cli_args.output).await,
+                        GetResources::Nodes => node::Nodes::list(&cli_args.output).await,
+                        GetResources::Node(args) => {
+                            node::Node::get(&args.node_id(), &cli_args.output).await
+                        }
+                        GetResources::BlockDevices(bdargs) => {
+                            blockdevice::BlockDevice::get_blockdevices(
+                                &bdargs.node_id(),
+                                &bdargs.all(),
+                                &cli_args.output,
+                            )
+                                .await
+                        }
+                    }
                 }
             },
             Operations::Drain(resource) => match resource {
diff --git a/k8s/plugin/src/resources/mod.rs b/k8s/plugin/src/resources/mod.rs
index f697561..db4fedb 100644
--- a/k8s/plugin/src/resources/mod.rs
+++ b/k8s/plugin/src/resources/mod.rs
@@ -6,6 +6,14 @@ pub mod objects;
 pub mod upgrade;
 use upgrade::UpgradeOperator;
 
+#[derive(clap::Subcommand, Debug)]
+pub enum GetResourcesK8s {
+    #[clap(flatten)]
+    GetRest(GetResources),
+    /// Get upgrade status
+    UpgradeStatus
+}
+
 /// The types of operations that are supported.
 #[derive(Parser, Debug)]
 pub enum Operations {
@@ -14,7 +22,7 @@ pub enum Operations {
     Drain(DrainResources),
     /// 'Get' resources.
     #[clap(subcommand)]
-    Get(GetResources),
+    Get(GetResourcesK8s),
     /// 'Scale' resources.
     #[clap(subcommand)]
     Scale(ScaleResources),
```

**Pull request merged**
