### PR TITLE
chore: update nixpkgs and rustc

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Rustc is now set to 2023-02-06 both for nightly and 1.67.0 for stable.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by chriswldenyer — APPROVED** [review]
Looks believable.

**Review by Abhinandan-Purkait — APPROVED** [review]
LGTM. Thanks

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
