### PR TITLE
ci(jenkins): fetch cron schedule from remote repo

### PR DESCRIPTION
**Pull request by tiagolobocastro**
And env variable "CRON_SCHEDULE_URL" is setup with the link to a yaml with the format: $branch-name:
  $jenkins-project-name: $schedule
  default: $schedule # for any other project name

Useful website to figure out the cron schedule syntax: https://crontab.cronhub.io/

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Folks, once this is approved I'll go ahead and manually merge this into all repo's and all branches..

**Review by blaisedias — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
