### PR TITLE
Fix python CI tests

### PR DESCRIPTION
**Pull request by tiagolobocastro**
fix(ha/node): don't replace path if nqn is not found
    
    In case of a race condition, the volume may be removed but the ha
    logic is still running. In this case it may attempt to connect the
    new path.
    This is a short term fix, probably we need a better approach.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    test(bdd): nvme list devices fix
    
    Existing nvme list devices was buggy, it does not filter subsystems.
    Instead, build device list from scratch.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
