### PR TITLE
ci(gha): don't build plugin binaries

### PR DESCRIPTION
**Pull request by tiagolobocastro**
The source has now been moved to the mayastor-extensions repo.

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by niladrih — APPROVED** [review]

**Review by avishnu — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
