### PR TITLE
feat(logs-for-ha-node): collect agent-ha-node logs

### PR DESCRIPTION
**Pull request by sinhaashish**
Signed-off-by: sinhaashish <ashi.sinha.87@gmail.com>

### CODE REVIEW

**Comment by sinhaashish** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]
Thank you 👍🏻

**Comment by avishnu** [comment]
Can we update for ha-cluster-agent logs as well?

**Comment by Abhinandan-Purkait** [comment]
> Can we update for ha-cluster-agent logs as well?

That would get automatically collected as its a part of the core-agent pod.

**Review by avishnu — APPROVED** [review]
lgtm

**Comment by sinhaashish** [comment]
bors merge

**Pull request merged**
