### PR TITLE
fix(rebuild/online_child): enforce max rebuilds

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Enforce the max number of rebuilds as part of online_child. For now addedd the registry as part of the child api, we might want to refactor this post release.

### CODE REVIEW

**Comment by abhilashshetty04** [comment]
Where did we enforce/check?

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
