### PR TITLE
Allow for custom names

### PR DESCRIPTION
**Pull request by tiagolobocastro**
feat(diskpool): allow for custom api name
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(csi): allow for custom plugin name
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(pstor/etcd): allow using custom prefix
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    feat(nvmf/nqn): allow using custom nvme nqn prefix
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]
cargo tests and openapi specs have mentions of `com.name` instead of openebs? That would be reverted I guess? I don't see the revertable commit.

**Comment by tiagolobocastro** [comment]
> cargo tests and openapi specs have mentions of `com.name` instead of openebs? That would be reverted I guess? I don't see the revertable commit.

That was intended

**Review by sinhaashish — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
