### PR TITLE
fix(plugin/snapshots): correct filter order and add new tests

### PR DESCRIPTION
**Pull request by dsharma-dc**

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by dsharma-dc** [comment]
bors merge

**Comment by dsharma-dc** [comment]
what's up bors?
bors cancel

**Comment by dsharma-dc** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
> what's up bors? bors cancel

Probably due to this: https://github.com/openebs/mayastor/pull/1422

**Pull request merged**
