### PR TITLE
chore: optimise the cargo bdd tests for volumes

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**

### CODE REVIEW

**Comment by Abhinandan-Purkait** [comment]
bors try

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors cancel

**Comment by Abhinandan-Purkait** [comment]
bors try

**Comment by Abhinandan-Purkait** [comment]
bors try

**Comment by tiagolobocastro** [comment]
We're trying a different approach instead of allow concurrent tests.
@Abhinandan-Purkait maybe add the restarting changes to deployer as another PR if still useful?

**Pull request closed without merging**
