### PR TITLE
feat(stats): add stats to v1 rpc module

### PR DESCRIPTION
**Pull request by abhilashshetty04**

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors merge

**Comment by abhilashshetty04** [comment]
bors merge

**Pull request merged**
