### PR TITLE
fix(snapshot): take into account snapshots for replica allocation

### PR DESCRIPTION
**Pull request by tiagolobocastro**
test(bdd): speedup tests by reusing clusters
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(uncordon): wrong error message on uncordon
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(snapshot): take into account snapshots for replica allocation
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
