### PR TITLE
test: use default agent list for default cases

### PR DESCRIPTION
**Pull request by chriswldenyer**
The default agent list in rust tests can usually be used.
This means the set of default agents can be changed at one point in the code, when needed.

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Review by niladrih — APPROVED** [review]
Maybe use a different commit message, e.g.:
```
test: use default agent list for default cases
```

**Comment by chriswldenyer** [comment]
> Maybe use a different commit message, e.g.:
> 
> ```
> test: use default agent list for default cases
> ```

Fixed.

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
