### PR TITLE
feat(plugin): add provisioning type field information for volumes

### PR DESCRIPTION
**Pull request by sinhaashish**
Screenshot 2022-10-11 at 12 13 13 PM

Signed-off-by: sinhaashish <ashi.sinha.87@gmail.com>

### CODE REVIEW

**Comment by sinhaashish** [comment]
bors try

**Comment by niladrih** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@GlennBullingham @sinhaashish doesn't seem to have permissions with bors?

**Review by niladrih — APPROVED** [review]

**Review by avishnu — APPROVED** [review]
lgtm

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Pull request merged**
