### PR TITLE
Replace deprecated Jaeger components with OpenTel 

### PR DESCRIPTION
**Pull request by tiagolobocastro**
fix(tracing): reduce tracing instrument spans to info
    
    New batch exporter used by opentel crate handles larger data better so we
    can be a bit more relaxed.
    This allows us to have good jaeger tracing and logs even with info.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    build: upgrade tracing and otel crates
    
    Upgrades all tracing and open telemetry crates.
    Replaces deprecated jaeger tracing create with generic opentel crate.
    Replaces deprecated jaeger jaeger with opentel collector.
    Removed openapi examples as they are not valid for our deps anymore.
    todo: upgrade openapi generator
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Review by dsharma-dc — APPROVED** [review]
How is this change tested for sanity?

**Review by niladrih — APPROVED** [review]
LGTM

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by sinhaashish — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> How is this change tested for sanity?

Manually for now :)
As for CI it's more complicated, need to ensure traces are being posted, which they are not at the moment, need to debug this.

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
