### PR TITLE
feat(images): build and push ha node image

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Review by mtzaurus — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
