### PR TITLE
chore(nix): update sources to the latest

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Updated Cargo to 1.59.0.
The nightly channel is now at 22-12-2021.

Make sure to update your local version of clippy and perhaps even clean the target folder to avoid conflicts.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
@Abhinandan-Purkait this should fix your git commit failing

**Comment by tiagolobocastro** [comment]
bors try

**Review by mtzaurus — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
