### PR TITLE
Cherry Pick PR 892

### PR DESCRIPTION
**Pull request by tiagolobocastro**
When a device is broken but the volume is not unstaged properly, the subsytem ends up lingering in the system.
If the device is staged again, the device is assined a different namespace id. Change the regex which is used in the device parameter fo account for this. Also extend the existing csi-node BDD testing.

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
Looks like the worker-4 is not configured correctly, I've removed it
bors merge

**Pull request merged**
