### PR TITLE
cherry-pick(fix): v1 to v2 migration, update labels put by control-plane

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**

### CODE REVIEW

**Comment by Abhinandan-Purkait** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
@tiagolobocastro The test seems to keep failing here, always.

```
FAILED tests/bdd/features/capacity/thin/volume/test_rebuild.py::test_rebuild_is_not_started_if_theres_no_space_in_the_pool - AssertionError: FIO failed, exit code: 1

assert 1 == 0
```

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Pull request merged**
